@echo off
echo Cambiando al directorio del proyecto...
cd /d "%~dp0"
echo Directorio actual: %cd%
echo Inicializando nuevo repositorio Git...
git init
echo Agregando archivos al repositorio...
git add .
echo Haciendo el primer commit...
git commit -m "Initial commit"
echo Configurando la rama principal como 'main'...
git branch -M main
echo Repositorio Git inicializado y primer commit realizado.
pause